### ISSUE TITLE
Attempting to Train Always Runs out of VRAM

### ISSUE THREAD

**Issue by arg274** [eloimoliner/denoising-historical-recordings#8]
Hello, I'm not quite sure on the resource requirements for this, but training seems to be completely unfeasible on lower to lower-mid-end systems. With the exception of Google Colab, all the other setups I've tried to train on seem to run out of VRAM. Colab Free seems to run out of physical RAM, on the other hand.

The environment is the exact same as the one in `environment.yml`. Noise data is the same as the one cited in the paper. Clean music data is a custom dataset, changing which did not seem to have any effect. The metadata for the noise dataset seemed to have some discrepancies, but those are a non-issue since it's a trivial cleanup.

The GPU memory usage seems to shoot up sharply at a point regardless of the hyperparameters and the size of the training data.

Tested on:

- Setup 1 (Local):

  - 1 x NVIDIA RTX 2080 (8 GB VRAM)
  - 32 GB Physical RAM

- Setup 2 (Azure ML Compute):
  - 1 x NVIDIA Tesla K80 (12 GB VRAM)
  - 56 GB Physical RAM

- Setup 3 (Google Colab Free):
  - 1 x NVIDIA Tesla T4 (16 GB VRAM)
  - 12 GB Physical RAM

Things that have been tried:

- Loading datasets using `with tf.device("CPU")` (This seems to keep the GPU usage low up to a certain point, but fails ultimately)
- Decreasing the batch size to 1
- Scaling the music dataset down massively (Initial size was 20 GB, but the final setting that was tested on was 500 MB)

Things that work:

- Inferencing
- CPU training

Traceback:

```
2023-04-23 05:53:46.684363: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at mirror_pad_op.cc:120 : Resource exhausted: OOM when allocating tensor with shape[2,96,429,1027] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Training epoch 0:   0%|                                                                                                                                                                                             | 0/2000 [03:57<?, ?it/s]
[2023-04-23 05:53:46,687][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "train.py", line 159, in main
    _main(args)
  File "train.py", line 153, in _main
    run(args)
  File "train.py", line 113, in run
    step_loss=trainer.distributed_training_step(iterator.get_next())
  File "/home/REDACTED/anaconda3/envs/historical_denoiser/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/REDACTED/anaconda3/envs/historical_denoiser/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/REDACTED/anaconda3/envs/historical_denoiser/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/REDACTED/anaconda3/envs/historical_denoiser/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/REDACTED/anaconda3/envs/historical_denoiser/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/REDACTED/anaconda3/envs/historical_denoiser/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/REDACTED/anaconda3/envs/historical_denoiser/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[2,96,429,1027] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node functional_1/multi_stage_denoise/StatefulPartitionedCall/decoder/d__block/i__block_7/dense_block_7/MirrorPad_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_distributed_training_step_25278]

Function call stack:
distributed_training_step
```

**Comment by eloimoliner** [comment]
Hi,

Thank you for trying this model and the information. I'm aware that the memory consumption is quite suboptimal on this model. I would like to develop a more efficient version but I don't know when I'll have the time to do that.

If you want to train a model by yourself, I would suggest reducing the parameter count. As I believe such a large model is not so necessary for this task. You can also try getting rid of the two U-nets thing, and just run one.

For your interest, there is a pytorch version of the denoiser in here: https://github.com/eloimoliner/bwe_historical_recordings  This one is trained at the sampling rate 22.05 kHz.
